version: '3.8'

services:

  db:
    image: postgres:15
    container_name: iiot_postgres_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mqtt_broker:
    image: eclipse-mosquitto:latest
    container_name: iiot_mqtt_broker
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt_data:/mosquitto/data
      - mqtt_log:/mosquitto/log
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -h localhost -p 1883 -t '$$SYS/#' -C 1 -W 3 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: iiot_fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - gateway_uploads:/code/uploads
    depends_on:
      db:
        condition: service_healthy
      mqtt_broker:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - MQTT_HOST=mqtt_broker
      - MQTT_PORT=1883
      - MQTT_USE_TLS=false
      - SECRET_KEY=${SECRET_KEY}

volumes:
  postgres_data:
  mqtt_data:
  mqtt_log:
  gateway_uploads: